# Generated by Django 3.0.7 on 2020-07-29 10:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='To Write with Markdown format', verbose_name='Contents'),
        ),
    ]
