# Generated by Django 3.0.7 on 2020-07-29 10:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200729_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='To Write with Markdown format', verbose_name='Content'),
        ),
    ]
