# Generated by Django 3.1.4 on 2020-12-06 05:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201206_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='To Write with Markdown format', verbose_name='Content'),
        ),
    ]
